#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

SECONDS=0

if [[ $git_cookies != 0 ]]; then

sudo touch /etc/mtab
sudo chmod 777 /etc/mtab

echo "$git_cookies" > ~/git_cookies.sh
bash ~/git_cookies.sh

fi

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-20.0 --git-lfs -g default,-mips,-darwin,-notdefault
#git clone https://github.com/Prashant-1695/local_manifest.git --depth 1 -b crdroid .repo/local_manifests

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j10

# extras
rm -rf hardware/qcom-caf/sdm660/display hardware/qcom-caf/sdm660/audio hardware/qcom-caf/sdm660/media
git clone -b sdm660-4.19-R-13 --depth=1 https://github.com/pix106/android_hardware_qcom-caf_display hardware/qcom-caf/sdm660/display
git clone -b sdm660-4.19-11.2.1.r1 --depth=1 https://github.com/pix106/android_hardware_qcom-caf_audio hardware/qcom-caf/sdm660/audio
git clone -b sdm660-4.19-11.2.1.r1 --depth=1 https://github.com/pix106/android_hardware_qcom-caf_media hardware/qcom-caf/sdm660/media

# tree
git clone --depth=1 https://github.com/lavender-4-19/device_xiaomi_lavender device/xiaomi/lavender -b 13-4.19
git clone --depth=1 https://github.com/lavender-4-19/vendor_xiaomi_lavender vendor/xiaomi/lavender -b 13-4.19
git clone --depth=1 https://github.com/lavender-4-19/device_xiaomi_sdm660-common vendor/xiaomi/lavender -b 13-4.19
git clone --depth=1 https://github.com/lavender-4-19/vendor_xiaomi_sdm660-common vendor/xiaomi/lavender -b 13-4.19
git clone --depth=1 https://github.com/pix106/android_kernel_xiaomi_southwest-4.19 kernel/xiaomi/sdm660 -b main

# patch
#cd /tmp/rom/system/libhidl && curl https://github.com/ArrowOS/android_system_libhidl/commit/fbdf10a33f546d202ae12b4b864177fea9faa998.patch | git am
#cd /tmp/rom/device/qcom/common && curl https://github.com/wHo-EM-i/android_device_qcom_common/commit/b3a612e836ddf3e9ac766612ee4bd9194b681c95.patch | git am
#cd /tmp/rom/bionic && curl https://github.com/wHo-EM-i/bionic/commit/61ea0bc221c8ae7992b44c58302e23ab3e748742.patch | git am
#cd /tmp/rom/hardware/libhardware && curl https://github.com/AOSPA/android_hardware_libhardware/commit/bec92996fbc143620da9a4a3c22a744958535ad5.patch | git am

. /tmp/ci/function
tg "$rom_name source sync completed!
Total Size: $(du -sh /tmp/rom | cut -d - -f 1 | cut -d / -f 1)
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
